#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

. $HOME/.config/bspwm/monitors.sh

#for pycharm and charles
wmname LG3D
#export _JAVA_AWT_WM_NONREPARENTING=1
#QT_AUTO_SCREEN_SCALE_FACTOR=1


xsetroot -cursor_name left_ptr &
. $HOME/.config/polybar/launch.sh &
pgrep -x xss-lock || xss-lock -- i3lock -c 000000 &
nitrogen --restore


bspc rule -a Gimp desktop='^5' state=tiling follow=off
#layer=below
#bspc rule -a Firefox-esr desktop='^2' follow=oncursor_name left_ptr &
#bspc rule -a Gedit desktop='^3' follow=on
#bspc rule -a Thunar desktop='^3'
bspc rule -a jetbrains-pycharm-ce desktop='^3' follow=off
bspc rule -a TelegramDesktop desktop='^4' follow=off
#bspc rule -a kitty desktop='^1' follow=off
bspc rule -a v2rayN desktop='^1' follow=off
bspc rule -a Google-chrome desktop='^2' state=tiling follow=off
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Peek state=floating


#$HOME/dev/check_hdmi.sh &
picom --config ~/.config/picom/picom.sample.conf -f &
v2rayn &
kitty &
#xbindkeys &
dunst &
flameshot &
parcellite &
nm-applet &
telegram-desktop &
#google-chrome &


bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#970ac2"
bspc config active_border_color "#c2500a"
bspc config focused_border_color "#35c20a"


