music_directory     "~/music"
playlist_directory  "~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
log_file            "~/.config/mpd/log"
pid_file            "~/.config/mpd/pid"
state_file          "~/.local/state/mpd/state"

auto_update "yes"

audio_output {
    type "pulse"
    name "PipeWire via Pulse"
}

audio_output {
    type "fifo"
    name "FIFO"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}

decoder {
    plugin "wildmidi"
    enabled "no"
}
