#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

. $HOME/.config/bspwm/monitors.sh
# на всякий случай, если скрипт не сработает
# bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

#for pycharm and charles
#wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
#QT_AUTO_SCREEN_SCALE_FACTOR=1


xsetroot -cursor_name left_ptr &
. $HOME/.config/polybar/launch.sh &
#nitrogen --restore
feh --bg-fill ~/iamges/chtulhu_v5.jpg

bspc rule -a Gimp desktop='^5' state=tiling follow=off
bspc rule -a jetbrains-pycharm desktop='^3' follow=off
bspc rule -a TelegramDesktop desktop='^4' follow=off
bspc rule -a v2rayN desktop='^1' follow=off
bspc rule -a Google-chrome desktop='^2' state=tiling follow=off
bspc rule -a Peek state=floating


picom --config ~/.config/picom/picom.sample.conf -f &
v2rayn &
kitty &
#xbindkeys &
dunst &
flameshot &
#parcellite &
diodon &
nm-applet &
telegram &
pgrep -x xss-lock || xss-lock -- i3lock -i ~/images/chtulhu_v5.png &


bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#970ac2"
bspc config active_border_color "#c2500a"
bspc config focused_border_color "#35c20a"


