;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
#primary = #F0C674
#primary = #34d628
primary = #35c20a
#secondary = #8ABEB7
#secondary = #ca28d6
secondary = #970ac2
alert = #f5160e
disabled = #707880
yellow = #fce00f
purple-dark = #410347

[bar/primary]
monitor = eDP-1
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.purple-dark}
foreground = ${colors.foreground}

line-size = 3pt

#border-size = 1pt
#border-color = ${colors.secondary}

padding-left = 1
padding-right = 1

module-margin = 1

#separator = |
#separator-foreground = ${colors.disabled}

wm-restack = bspwm

font-0 = monospace;2
font-1 = FontAwesome:style=Regular;2
#font-2 = Font Awesome 6 Brands Regular:style=Regular
#font-3 = Font Awesome v4 Compatibility Regular:style=Regular
#font-4 = Font Awesome 6 Free Regular:style=Regular

#modules-left = xworkspaces xwindow
modules-left = date tray xwindow
modules-center = bspwm
modules-right = filesystem xkeyboard pulseaudio backlight temperature battery memory cpu powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

#tray-position = center
#tray-radius = 6
#tray-offset-x = -300

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

override-redirect = false

[bar/secondary]
monitor = DP-2
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.purple-dark}
foreground = ${colors.foreground}

line-size = 3pt

#border-size = 1pt
#border-color = ${colors.secondary}

padding-left = 1
padding-right = 1

module-margin = 1

#separator = |
#separator-foreground = ${colors.disabled}

wm-restack = bspwm

font-0 = monospace;2
font-1 = FontAwesome:style=Regular;2
#font-2 = Font Awesome 6 Brands Regular:style=Regular
#font-3 = Font Awesome v4 Compatibility Regular:style=Regular
#font-4 = Font Awesome 6 Free Regular:style=Regular

#modules-left = xworkspaces xwindow
modules-center = bspwm 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[bar/third]
monitor = HDMI-0
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.purple-dark}
foreground = ${colors.foreground}

line-size = 3pt

#border-size = 1pt
#border-color = ${colors.secondary}

padding-left = 1
padding-right = 1

module-margin = 1

#separator = |
#separator-foreground = ${colors.disabled}

wm-restack = bspwm

font-0 = monospace;2
font-1 = FontAwesome:style=Regular;2
#font-2 = Font Awesome 6 Brands Regular:style=Regular
#font-3 = Font Awesome v4 Compatibility Regular:style=Regular
#font-4 = Font Awesome 6 Free Regular:style=Regular

#modules-left = xworkspaces xwindow
modules-center = bspwm 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[module/bspwm]
type = internal/bspwm
#monitor = eDP1
#pin-workspaces = true
enable-scroll = false
#fuzzy-match = true
ws-icon-0 = I; 
ws-icon-1 = II;  
ws-icon-2 = III; 
ws-icon-3 = IV; 
ws-icon-4 = V; 
ws-icon-default =  

format = <label-state> <label-mode>

label-focused = %icon%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background-alt}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-underline = ${colors.disabled}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.secondary}
label-urgent-underline = ${colors.secondary}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xworkspaces]
#type = internal/xworkspaces

#label-active = %name%
#label-active-background = ${colors.background-alt}
#label-active-underline= ${colors.primary}
#label-active-padding = 1

#label-occupied = %name%
#label-occupied-padding = 1

#label-urgent = %name%
#label-urgent-background = ${colors.alert}
#label-urgent-padding = 1

#label-empty = %name%
#label-empty-foreground = ${colors.disabled}
#label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-maxlen = 30

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#35c20a}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

#label-muted = muted
label-muted =  
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/temperature]
type = internal/temperature
interval = 5
thermal-zone = 0
#msi 
zone-type = x86_pkg_temp
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input
#hwmon-path = ${env:HWMON_PATH}
#hwmon-path = /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input
base-temperature = 20
warn-temperature = 60
units = true
format = <label>
label = %{F-} %temperature-c%
label-foreground = ${colors.primary}
format-warn = <label-warn>
label-warn = %{F-} %temperature-c%
label-warn-foreground = ${colors.alert}


[module/battery]
type = internal/battery
full-at = 100
low-at = 10
#msi
battery = BAT1
adapter = ADP1
poll-interval = 5
format-charging = <label-charging>
format-charging-prefix = " "
format-charging-prefix-foreground = ${colors.yellow}
format-discharging = <label-discharging>
format-discharging-prefix = " "
format-discharging-prefix-foreground = ${colors.primary}
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
format-full = <label-full> 
format-full-prefix = " "
format-full-prefix-foreground = ${colors.primary}
label-low = %percentage%%
format-low = <label-low>
format-low-prefix = " "
format-low-prefix-foreground = ${colors.alert}

[module/memory]
type = internal/memory
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

#[network-base]
#type = internal/network
#interval = 5
#format-connected = <label-connected>
#format-disconnected = <label-disconnected>
#label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

#[module/wlan]
#inherit = network-base
#interface-type = wireless
#label-connected = %{F#35c20a}%ifname%%{F-} %essid% %local_ip%
#label-connected = %{F-} %essid%
#label-connected-foreground = ${colors.primary}

[module/eth]
#inherit = network-base
#interface-type = wired
#label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight
#msi
card = intel_backlight
use-actual-brightness = true
enable-scroll = true
format = <label>
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/tray]
type = internal/tray
format-margin = 8px
tray-spacing = 8px

[module/powermenu]
type = custom/text
click-left = ~/.config/rofi/powermenu.sh
format = ""
format-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
